package main

// RUNTIME COMPATIBILITY — the generated scaffolding must match the RESOLVED soroq_flutter.
//
// `soroq release --platforms=ios` generates a bootstrap that calls into the soroq_flutter runtime. If
// the project resolved an OLDER soroq_flutter than the CLI generates against, the build fails deep
// inside the Xcode phase with:
//
//	.soroq/generated/soroq_bootstrap.g.dart:65:11: Error: Method not found: 'soroqCommitStableOnHealthyFrame'.
//	Target kernel_snapshot_program failed: Exception
//
// which is reported to the developer as "flutter build ios failed at a later (Xcode/codesign) stage" —
// a message that points at signing and says nothing about a version mismatch.
//
// HOW THE CHECK WORKS, AND WHY NOT A TEXT SCAN.
//
// The first version grepped the resolved package for each symbol name. That accepts things it must
// not: a name appearing only in a comment or a string; a PRIVATE declaration (`_restorePrepare`); a
// declaration that exists but is not exported from the package's public library; the right name on the
// wrong owner; and the right name with the wrong signature. Every one of those still fails the real
// build, so a check that passes them is worse than no check — it converts a clear refusal into the
// confusing Xcode failure it was written to prevent.
//
// So compatibility is decided by COMPILING a generated probe against the project's own resolved
// packages, with the same gen_kernel the build uses. The probe calls each required API the way the
// generated scaffolding calls it — through its owner, with its argument shape — so owner, signature,
// visibility and export are all decided by the Dart front end rather than by pattern matching. If the
// probe compiles, the scaffolding will too.

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// freehandRuntimeAPI is one API the generated scaffolding depends on, together with the probe
// statement that pins its owner and signature.
type freehandRuntimeAPI struct {
	symbol string // the identifier, used to attribute compiler errors
	why    string // what the generated code uses it for
	stmt   string // Dart that exercises it exactly as the generated code does
}

// freehandRuntimeAPIs lists what the CURRENT generator emits. Adding a call to the bootstrap or
// activator templates means adding it here, so an old runtime is refused with a message naming it.
func freehandRuntimeAPIs() []freehandRuntimeAPI {
	return []freehandRuntimeAPI{
		{
			symbol: "restorePrepare",
			why:    "prepares the persisted candidate before first-frame activation",
			// Called ON the controller: pins the owner, not just the name.
			stmt: "await c.restorePrepare();",
		},
		{
			symbol: "soroqActivateRestoredAfterFirstFrame",
			why:    "defers activation until after the first frame",
			stmt:   "await soroqActivateRestoredAfterFirstFrame(c);",
		},
		{
			symbol: "soroqCommitStableOnHealthyFrame",
			why:    "marks a patch stable once a healthy frame has rasterized",
			stmt:   "soroqCommitStableOnHealthyFrame(c, 1);",
		},
		{
			symbol: "SoroqFreehandActivator",
			why:    "the freehand identity-redirect capability interface",
			stmt:   "final SoroqFreehandActivator? a = null; if (a != null) {}",
		},
	}
}

// freehandRuntimeProbeSource renders the probe. It is compiled, never shipped, and never written into
// the customer's lib/.
func freehandRuntimeProbeSource() string {
	var b strings.Builder
	b.WriteString("// GENERATED by `soroq release` to verify the resolved soroq_flutter runtime.\n")
	b.WriteString("// Compiled and discarded; never shipped, never written into the project's lib/.\n")
	b.WriteString("// ignore_for_file: unused_local_variable, unused_element\n")
	b.WriteString("import 'package:soroq_flutter/soroq_flutter.dart';\n\n")
	b.WriteString("Future<void> _soroqRuntimeProbe(SoroqEngineLaneController c) async {\n")
	for _, api := range freehandRuntimeAPIs() {
		b.WriteString("  " + api.stmt + "\n")
	}
	b.WriteString("}\n\nvoid main() {}\n")
	return b.String()
}

// verifyFreehandRuntimeCompatibility refuses to build when the RESOLVED soroq_flutter does not provide
// every API the generated scaffolding calls, with the owner and signature it calls them by.
func verifyFreehandRuntimeCompatibility(projectDir, flutterRoot string) error {
	pkgConfig := filepath.Join(projectDir, ".dart_tool", "package_config.json")
	if !fileExists(pkgConfig) {
		return fmt.Errorf("no %s; run `flutter pub get` before releasing", pkgConfig)
	}

	tmpDir, err := os.MkdirTemp("", "soroq-runtime-probe-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	probe := filepath.Join(tmpDir, "soroq_runtime_probe.dart")
	if err := os.WriteFile(probe, []byte(freehandRuntimeProbeSource()), 0o644); err != nil {
		return err
	}

	aot := flutterDartAotRuntime(flutterRoot)
	genKernel := flutterGenKernelSnapshot(flutterRoot)
	platformRel, err := flutterProfilePlatformDillRel(flutterRoot)
	if err != nil {
		return fmt.Errorf("resolve flutter platform dill: %w", err)
	}
	platform := filepath.Join(flutterRoot, platformRel)
	for name, p := range map[string]string{
		"dartaotruntime": aot, "gen_kernel snapshot": genKernel, "platform dill": platform,
	} {
		if !fileExists(p) {
			return fmt.Errorf("cannot verify the resolved runtime: %s missing at %s", name, p)
		}
	}

	out := filepath.Join(tmpDir, "probe.dill")
	cmd := exec.Command(aot, "--disable-dart-dev", genKernel,
		"--target", "flutter",
		"--platform", platform,
		"--packages", pkgConfig,
		"--no-aot", "--no-embed-sources",
		"--output", out,
		probe,
	)
	cmd.Dir = projectDir
	combined, runErr := cmd.CombinedOutput()
	if runErr == nil && fileExists(out) {
		return nil
	}

	return fmt.Errorf("%s", freehandRuntimeIncompatibilityMessage(projectDir, string(combined)))
}

// freehandRuntimeIncompatibilityMessage turns front-end output into an actionable refusal, attributing
// each required API the compiler complained about.
func freehandRuntimeIncompatibilityMessage(projectDir, compilerOutput string) string {
	var missing []freehandRuntimeAPI
	for _, api := range freehandRuntimeAPIs() {
		if strings.Contains(compilerOutput, api.symbol) {
			missing = append(missing, api)
		}
	}

	var b strings.Builder
	b.WriteString("the resolved soroq_flutter runtime does not provide the API this CLI's generated\n")
	b.WriteString("scaffolding calls (verified by compiling a probe against the project's own resolution).\n")
	if lib, err := resolvedPackageLibDir(projectDir, "soroq_flutter"); err == nil {
		fmt.Fprintf(&b, "  resolved package: %s\n", lib)
	}
	if len(missing) > 0 {
		b.WriteString("  unsatisfied API:\n")
		for _, m := range missing {
			fmt.Fprintf(&b, "    - %s  (%s)\n", m.symbol, m.why)
		}
	}
	b.WriteString("\nCompiler output:\n")
	for _, line := range strings.Split(strings.TrimSpace(compilerOutput), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		b.WriteString("  " + line + "\n")
	}
	b.WriteString("\nBuilding would fail inside the Dart front end against .soroq/generated/soroq_bootstrap.g.dart,\n")
	b.WriteString("which surfaces as an Xcode/codesign failure and is not actionable. Refusing here instead.\n")
	b.WriteString("\nFix: resolve a soroq_flutter that provides these APIs and re-run `flutter pub get`.")
	return b.String()
}

// resolvedPackageLibDir returns the lib/ directory of a package as the project actually resolved it,
// read from .dart_tool/package_config.json. That file is what the compiler uses, so it is the only
// honest source: pubspec.yaml states a constraint, not a resolution.
func resolvedPackageLibDir(projectDir, packageName string) (string, error) {
	cfgPath := filepath.Join(projectDir, ".dart_tool", "package_config.json")
	raw, err := os.ReadFile(cfgPath)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", cfgPath, err)
	}
	var cfg struct {
		Packages []struct {
			Name       string `json:"name"`
			RootURI    string `json:"rootUri"`
			PackageURI string `json:"packageUri"`
		} `json:"packages"`
	}
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return "", fmt.Errorf("parse %s: %w", cfgPath, err)
	}
	for _, p := range cfg.Packages {
		if p.Name != packageName {
			continue
		}
		root := strings.TrimPrefix(p.RootURI, "file://")
		if !filepath.IsAbs(root) {
			root = filepath.Join(projectDir, ".dart_tool", filepath.FromSlash(root))
		}
		sub := p.PackageURI
		if strings.TrimSpace(sub) == "" {
			sub = "lib/"
		}
		return filepath.Clean(filepath.Join(root, filepath.FromSlash(sub))), nil
	}
	return "", fmt.Errorf("package %q is not in %s; run `flutter pub get`", packageName, cfgPath)
}
