package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCallingConventionGate_ClassifiesWhatAPreCapabilityBaseCompiledBoxed(t *testing.T) {
	whole := map[string]bool{"package:app/main.dart": true}
	changed := []string{
		"package:app/main.dart::Cell::build",             // public class, whole lib: callable
		"package:app/main.dart::Student::get:average",    // callable getter
		"package:app/main.dart::::benchSmallCalls",       // public top-level, whole lib
		"package:app/main.dart::_HomeState::build",       // private State override of State.build
		"package:app/main.dart::_HomeState::initState",   // ditto
		"package:app/main.dart::_BenchPageState::runAll", // private class, own selector: register CC
		"package:app/main.dart::_Box::area",              // private class, own selector (unboxed double)
		"package:dep/src/x.dart::Helper::run",            // scoped dependency, not whole
		"package:dep/src/x.dart::::topLevel",             // scoped dependency top-level
	}
	got := freehandCallingConventionUnsafe(changed, whole)
	want := []string{
		"package:app/main.dart::_BenchPageState::runAll",
		"package:app/main.dart::_Box::area",
		"package:dep/src/x.dart::::topLevel",
		"package:dep/src/x.dart::Helper::run",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("unsafe = %v, want %v", got, want)
	}
	// A v1 base lists every package library whole.
	if got := freehandCallingConventionUnsafe([]string{"package:dep/src/x.dart::Helper::run", "package:dep/src/x.dart::_P::run"}, nil); len(got) != 1 || got[0] != "package:dep/src/x.dart::_P::run" {
		t.Fatalf("v1 classification wrong: %v", got)
	}
}

func TestCallingConventionGate_ReadsWholeCallableLibrariesOnly(t *testing.T) {
	y := "# Generated by Soroq. Do not edit.\ncallable:\n  - library: 'dart:core'\n  - library: 'package:app/main.dart'\n" +
		"  - library: 'package:flutter/src/widgets/framework.dart'\n    class: ['State']\n" +
		"extendable:\n  - library: 'package:other/o.dart'\ncan-be-used-as-type:\n  - library: 'package:types/t.dart'\n"
	p := filepath.Join(t.TempDir(), "base_contract.yaml")
	if err := os.WriteFile(p, []byte(y), 0o600); err != nil {
		t.Fatal(err)
	}
	whole, err := freehandCallableWholeLibraries(p)
	if err != nil {
		t.Fatal(err)
	}
	if !whole["dart:core"] || !whole["package:app/main.dart"] || whole["package:flutter/src/widgets/framework.dart"] ||
		whole["package:other/o.dart"] || whole["package:types/t.dart"] || len(whole) != 2 {
		t.Fatalf("whole callable libraries = %v", whole)
	}
}
