package main

// AN ORDINARY `flutter pub get` MUST NOT BREAK PATCHING.
//
// The base graph of a release is resolved by the pinned Soroq toolchain's Flutter. Its SDK pulls in
// packages a developer's own Flutter may not (objective_c, code_assets, hooks, record_use, pub_semver,
// yaml, logging). When the candidate graph was read from the DEVELOPER's pubspec.lock, the two sides
// came from two different SDKs, so running `flutter pub get` -- an entirely ordinary command -- produced
// a descriptor claiming seven packages had been "removed from the runtime dependency graph" and a
// plugin had been "introduced". The eligibility gate then correctly refused a patch whose only real
// change was one string, and named packages the developer had never heard of.
//
// Worse, there was no way back: the system Flutter cannot reproduce the toolchain's resolution, and
// `soroq release` refuses to overwrite an immutable baseline, so the project was stuck.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeProjectFiles(t *testing.T, dir string, lock string) {
	t.Helper()
	mustWriteFile(t, filepath.Join(dir, "pubspec.yaml"), "name: app\nversion: 1.0.0+1\n")
	mustWriteFile(t, filepath.Join(dir, "pubspec.lock"), lock)
	if err := os.MkdirAll(filepath.Join(dir, ".dart_tool"), 0o755); err != nil {
		t.Fatal(err)
	}
	mustWriteFile(t, filepath.Join(dir, ".dart_tool", "package_config.json"),
		`{"configVersion":2,"packages":[{"name":"app","rootUri":"../","packageUri":"lib/"}]}`)
}

const developerLock = `# Generated by pub
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "aaaa"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
sdks:
  dart: ">=3.5.0 <4.0.0"
`

// The toolchain resolves the same project plus SDK-adjacent packages the developer's Flutter omits.
const toolchainLock = `# Generated by pub
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "aaaa"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
  objective_c:
    dependency: transitive
    description:
      name: objective_c
      sha256: "bbbb"
      url: "https://pub.dev"
    source: hosted
    version: "9.5.0"
sdks:
  dart: ">=3.5.0 <4.0.0"
`

// The pinned lock is PREFERRED when a build resolution has produced one, so both sides of a patch are
// resolved from the same SDK's output.
// Proven by discriminator rather than by package contents: the graph filters to packages reachable from
// the root, so a fixture's package list would prove nothing about WHICH lock was opened. A pinned lock
// that cannot parse must surface as an error — which it can only do if it was the file that was read.
func TestPinnedLockIsPreferredOverTheDevelopersLock(t *testing.T) {
	dir := t.TempDir()
	writeProjectFiles(t, dir, developerLock) // a perfectly valid project lock
	mustWriteFile(t, pinnedLockPath(dir), "\x00not: [valid: yaml\n")

	if _, err := resolveRuntimeGraphPinned(dir); err == nil {
		t.Fatal("resolution succeeded despite an unparseable pinned lock, so it read the developer's " +
			"lock instead; both sides of a patch must come from one SDK's resolution")
	}
}

// The developer's own lock is used only when no build resolution has run.
func TestWithoutAPinnedLockTheProjectLockIsUsed(t *testing.T) {
	dir := t.TempDir()
	writeProjectFiles(t, dir, developerLock)

	g, err := resolveRuntimeGraphPinned(dir)
	if err != nil {
		t.Fatalf("fallback resolution failed: %v", err)
	}
	if _, ok := g.Packages["objective_c"]; ok {
		t.Error("no pinned lock exists, so the project's own lock must be used verbatim")
	}
}

// THE ACTUAL TRAP. A developer edits pubspec.yaml, runs `flutter pub get`, and their lock loses the
// toolchain's SDK-adjacent packages. Resolution must still see the toolchain's view, so the descriptor
// shows only the intended change instead of a wall of false removals.
func TestAnOrdinaryPubGetDoesNotChangeWhatResolutionSees(t *testing.T) {
	dir := t.TempDir()
	writeProjectFiles(t, dir, toolchainLock)
	mustWriteFile(t, pinnedLockPath(dir), toolchainLock)

	before, err := resolveRuntimeGraphPinned(dir)
	if err != nil {
		t.Fatal(err)
	}

	// The developer runs `flutter pub get` with their own Flutter: the project lock is rewritten and
	// loses objective_c. Soroq's pinned copy is untouched -- it lives under .soroq/.
	mustWriteFile(t, filepath.Join(dir, "pubspec.lock"), developerLock)

	after, err := resolveRuntimeGraphPinned(dir)
	if err != nil {
		t.Fatalf("resolution broke after an ordinary pub get: %v", err)
	}
	if len(before.Packages) != len(after.Packages) {
		t.Fatalf("an ordinary `flutter pub get` changed the resolved graph from %d to %d packages; "+
			"that is the false-diff that refused patches naming packages the developer never added",
			len(before.Packages), len(after.Packages))
	}
	if before.GraphDigest != after.GraphDigest {
		t.Error("graph digest changed after a pub get the developer was entitled to run")
	}
}

// Soroq's pinned copy must never be the developer's file. Writing the project's pubspec.lock is what
// would make Soroq responsible for a developer's source control state.
func TestThePinnedLockLivesUnderSoroqNotTheProjectRoot(t *testing.T) {
	dir := t.TempDir()
	got := pinnedLockPath(dir)
	if got == filepath.Join(dir, "pubspec.lock") {
		t.Fatal("the pinned lock must not be the developer's pubspec.lock")
	}
	if rel, _ := filepath.Rel(dir, got); filepath.Dir(rel) == "." {
		t.Errorf("the pinned lock must not sit in the project root: %s", rel)
	}
	if !containsPathSegment(got, ".soroq") {
		t.Errorf("the pinned lock must live under .soroq/ (git-ignored): %s", got)
	}
}

func containsPathSegment(p, seg string) bool {
	for _, s := range filepath.SplitList(p) {
		_ = s
	}
	dir := p
	for {
		if filepath.Base(dir) == seg {
			return true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return false
		}
		dir = parent
	}
}

// The isolated workspace must SEED from Soroq's pinned lock, not the developer's. Persisting a pinned
// lock is only half the fix: if the next resolution seeds from a project lock that `flutter pub get`
// stripped of toolchain-only packages, it re-imports the damage and the patch is refused with a wall of
// "was removed from the runtime dependency graph" errors naming packages the developer never added.
func TestWorkspaceSeedsFromThePinnedLockNotTheProjectLock(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "pubspec.yaml"), "name: app\n")
	mustWriteFile(t, filepath.Join(dir, "pubspec.lock"), developerLock)
	mustWriteFile(t, pinnedLockPath(dir), toolchainLock)

	var seeded string
	orig := runFlutterPubGetIn
	runFlutterPubGetIn = func(ws string) error {
		b, err := os.ReadFile(filepath.Join(ws, "pubspec.lock"))
		if err == nil {
			seeded = string(b)
		}
		// Produce the minimum the caller needs so the run reaches its assertions.
		if err := os.MkdirAll(filepath.Join(ws, ".dart_tool"), 0o755); err != nil {
			return err
		}
		return os.WriteFile(filepath.Join(ws, ".dart_tool", "package_config.json"),
			[]byte(`{"configVersion":2,"packages":[{"name":"app","rootUri":"../","packageUri":"lib/"}]}`), 0o644)
	}
	defer func() { runFlutterPubGetIn = orig }()

	if _, _, err := resolveSoroqBuildInputs(dir, t.TempDir()); err != nil {
		t.Fatalf("resolution failed: %v", err)
	}
	if !strings.Contains(seeded, "objective_c") {
		t.Error("the workspace was seeded from the developer's lock; a `flutter pub get` would then " +
			"strip toolchain-only packages and the next patch would be refused for removing them")
	}
}
