package main

// ISOLATED DEPENDENCY RESOLUTION — the Soroq build gets the packages it needs WITHOUT touching a single
// file the developer commits.
//
// What this replaces. The iOS hard-OTA activator imports `package:dynamic_modules/dynamic_modules.dart`,
// a package that is not on pub.dev. The CLI used to make that resolvable by writing
//
//	dependencies:
//	  dynamic_modules:
//	    path: /Users/<developer>/.soroq/dynamic_modules
//
// into the customer's pubspec.yaml and running `flutter pub get`. That is wrong in four separate ways:
// the path is machine-specific, so no teammate or CI runner can resolve the project; pubspec.yaml and
// pubspec.lock are files developers commit, and Soroq was rewriting both; the lock was re-resolved by
// the frontend's newer Dart SDK, after which the developer's own Flutter could no longer `pub get`,
// `analyze` or `test` the project at all; and it made a build side-effect out of project metadata.
//
// Why a package at all. The primitive imports `dart:_internal`, and the front end rejects that from a
// `file:` URI ("Can't access platform private library"), so the source cannot simply be dropped next to
// the generated bootstrap and imported relatively. It must be reachable as a `package:` URI, which
// means an entry in package_config.json.
//
// The mechanism. package_config.json lives under .dart_tool/ — build output, git-ignored, and
// regenerated by any `pub get`. So resolution happens in a THROWAWAY workspace:
//
//  1. a temp directory gets a COPY of the project's pubspec.yaml (plus its pubspec.lock, so resolution
//     starts from the developer's own pins) with the dynamic_modules path dependency added to the COPY;
//  2. the frontend Flutter runs `pub get` there — rewriting that copy's lock, never the project's;
//  3. the resulting package_config.json is rewritten so the root package points at the REAL project,
//     and installed into the project's .dart_tool/ atomically;
//  4. the workspace is removed, on success and on failure alike;
//  5. the build then runs with --no-pub so Flutter does not regenerate what we just installed.
//
// A useful side effect: because the workspace resolves with the FRONTEND's Flutter, the installed
// package_config binds the frontend's framework sources — which is what the local-engine build needs.
// Reusing the developer's own package_config would pair their framework with the Soroq engine, the
// exact mismatch that produces "A value of type 'Tristate' can't be assigned to a variable of type
// 'bool'" deep inside semantics.dart.

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"soroq/backend/internal/depgraph"
	"strings"
)

// runFlutterPubGetIn runs `flutter pub get` in dir with the Soroq frontend Flutter. Overridable in tests.
var runFlutterPubGetIn = func(dir string) error {
	flutterBin, err := resolveSoroqFlutterBin()
	if err != nil {
		if path, lookErr := exec.LookPath("flutter"); lookErr == nil {
			flutterBin = path
		} else {
			return fmt.Errorf("flutter not found for dependency resolution: %w", err)
		}
	}
	cmd := exec.Command(flutterBin, "pub", "get")
	cmd.Dir = dir
	// The workspace resolve is plumbing, not something the developer asked to see; only its failure is.
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// prepareSoroqBuildResolution makes the Soroq-only packages resolvable for a build of projectDir,
// WITHOUT modifying pubspec.yaml, pubspec.lock, or anything else the developer tracks.
//
// It returns the absolute path of the extracted dynamic_modules package.
func prepareSoroqBuildResolution(projectDir string) (string, error) {
	installDir, err := dynamicModulesInstallDir()
	if err != nil {
		return "", err
	}
	embeddedSHA, err := embeddedDynamicModulesLibSHA256()
	if err != nil {
		return "", err
	}
	// SAME-PROJECT SERIALISATION. Two concurrent builds of ONE project would otherwise interleave
	// destructively: the lock sidecar is a single fixed path, so B could park A's already-rewritten lock
	// over A's saved original and then "restore" the rewritten bytes — silently losing the developer's
	// lock. The isolated workspaces are per-build, but the sidecar and the installed package_config are
	// project-scoped, so those two steps must not overlap.
	unlock, err := acquireProjectBuildLock(projectDir)
	if err != nil {
		return "", err
	}
	defer unlock()

	// Repair a lock left rewritten by an interrupted earlier run before doing anything else.
	if err := restoreInterruptedLock(projectDir); err != nil {
		return "", err
	}
	// Content-addressed by the embedded source sha: concurrent extractions of the same CLI version
	// converge on identical bytes rather than corrupting each other.
	if _, err := extractDynamicModulesIfStale(installDir, embeddedSHA); err != nil {
		return "", err
	}
	// Plugin scaffolding must match the resolved plugins, and only `flutter pub get` in the project can
	// produce it. The lock it rewrites is put back, crash-safely.
	if err := runPluginInjection(projectDir); err != nil {
		return "", err
	}

	configBytes, pinnedLock, err := resolveSoroqBuildInputs(projectDir, installDir)
	if err != nil {
		return "", err
	}
	if err := installPackageConfig(projectDir, configBytes); err != nil {
		return "", err
	}
	// Persist the lock the pinned toolchain resolved, NEXT TO the package_config it belongs with.
	//
	// installPackageConfig writes the toolchain's package_config into the project, but the project's
	// pubspec.lock stays the developer's. Resolving a dependency graph from that pair mixes two SDKs'
	// output: the graph would claim packages the package_config resolves are absent from the lock, and
	// vice versa. Keeping the matching lock here lets the graph be read from a consistent pair without
	// ever touching what the developer owns.
	if len(pinnedLock) > 0 {
		if err := writePinnedLock(projectDir, pinnedLock); err != nil {
			return "", err
		}
	}
	return installDir, nil
}

// pinnedLockPath is where the toolchain-resolved lock lives. Under .soroq/ (git-ignored), never in the
// project root: this is Soroq's copy, and the developer's pubspec.lock is read-only to us.
func pinnedLockPath(projectDir string) string {
	return filepath.Join(projectDir, ".soroq", "build", "pinned-pubspec.lock")
}

func writePinnedLock(projectDir string, lock []byte) error {
	path := pinnedLockPath(projectDir)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := writeFileAtomic(path, lock); err != nil {
		return fmt.Errorf("persist the toolchain-pinned pubspec.lock: %w", err)
	}
	return nil
}

// resolveRuntimeGraphPinned resolves the dependency graph from the TOOLCHAIN-PINNED lock and
// package_config when a build resolution has produced them, and only otherwise from the project's own.
//
// This is what makes an ordinary `flutter pub get` harmless. Before it, the base graph came from the
// toolchain's Flutter and the candidate graph from whatever Flutter the developer had, so SDK-adjacent
// packages the toolchain pulls in (objective_c, code_assets, hooks, record_use) appeared as removals and
// the eligibility gate refused the patch -- naming packages the developer had never heard of, with no
// documented way back.
func resolveRuntimeGraphPinned(projectDir string) (depgraph.Graph, error) {
	lock := pinnedLockPath(projectDir)
	cfg := filepath.Join(projectDir, ".dart_tool", "package_config.json")
	if _, err := os.Stat(lock); err == nil {
		return depgraph.ResolveAt(projectDir, lock, cfg)
	}
	return depgraph.Resolve(projectDir)
}

// resolveSoroqPackageConfig resolves the project's dependencies PLUS dynamic_modules in a throwaway
// workspace and returns the package_config.json bytes, rewritten to point at the real project.
func resolveSoroqPackageConfig(projectDir, dynamicModulesDir string) ([]byte, error) {
	cfg, _, err := resolveSoroqBuildInputs(projectDir, dynamicModulesDir)
	return cfg, err
}

// resolveSoroqBuildInputs performs the isolated, TOOLCHAIN-PINNED resolution once and returns both
// artifacts it produces: the rewritten package_config.json and the pubspec.lock that resolution pinned.
//
// The lock is returned rather than thrown away because the dependency graph on BOTH sides of a patch
// has to come from the same SDK. The base graph is resolved here at release time; if the candidate side
// later reads the developer's own lock instead, the two graphs were produced by two different Flutter
// versions and every SDK-adjacent package the toolchain pulls in (objective_c, code_assets, hooks,
// record_use) reads as a removal. That is a false refusal caused by a developer running `flutter pub
// get` -- an entirely ordinary command -- so the candidate side uses this lock too.
func resolveSoroqBuildInputs(projectDir, dynamicModulesDir string) (cfgBytes []byte, lockBytes []byte, err error) {
	projectDir, err = filepath.Abs(projectDir)
	if err != nil {
		return nil, nil, err
	}
	pubspecPath := filepath.Join(projectDir, "pubspec.yaml")
	pubspec, err := os.ReadFile(pubspecPath)
	if err != nil {
		return nil, nil, fmt.Errorf("read %s: %w", pubspecPath, err)
	}
	packageName := strings.TrimSpace(parseTopLevelYaml(pubspec)["name"])
	if packageName == "" {
		return nil, nil, fmt.Errorf("%s has no top-level package name", pubspecPath)
	}

	// A unique workspace per build: two concurrent builds of the SAME project cannot share or overwrite
	// each other's resolution. MkdirTemp guarantees the uniqueness.
	workspace, err := os.MkdirTemp("", "soroq-resolve-")
	if err != nil {
		return nil, nil, err
	}
	// Removed on success AND on every failure path below, so no temporary state survives an error or a
	// mid-resolve abort.
	defer os.RemoveAll(workspace)

	withDep, _, err := pubspecWithPathDependency(string(pubspec), "dynamic_modules", dynamicModulesDir)
	if err != nil {
		return nil, nil, err
	}
	// Relative path dependencies are relative to the DEVELOPER'S project, not to this temp workspace.
	// Without this, any monorepo or locally-developed plugin fails to resolve here while resolving
	// fine in the developer's own tree.
	withDep = pubspecWithAbsolutePathDependencies(withDep, projectDir)
	if err := os.WriteFile(filepath.Join(workspace, "pubspec.yaml"), []byte(withDep), 0o644); err != nil {
		return nil, nil, err
	}
	// Seed the workspace so resolution starts from existing pins instead of drifting to the newest of
	// everything. PREFER SOROQ'S OWN PINNED LOCK over the developer's.
	//
	// Seeding from the developer's lock propagates any damage in it. A developer who runs
	// `flutter pub get` with their own Flutter drops the toolchain-only packages (dynamic_modules and
	// its transitives: code_assets, hooks, logging, objective_c, pub_semver, record_use, yaml); seeding
	// the isolated workspace from that lock reproduced the loss inside the workspace, and the patch was
	// then refused with seven "was removed from the runtime dependency graph" errors naming packages the
	// developer never added. Persisting a pinned lock was only half the fix — it also has to be the
	// SEED, or the next resolution re-imports the damage.
	//
	// Falls back to the developer's lock when no pinned lock exists yet (the first release), and to no
	// seed at all when neither exists — pub then resolves from scratch.
	seed := pinnedLockPath(projectDir)
	if _, err := os.Stat(seed); err != nil {
		seed = filepath.Join(projectDir, "pubspec.lock")
	}
	if lock, err := os.ReadFile(seed); err == nil {
		if err := os.WriteFile(filepath.Join(workspace, "pubspec.lock"), lock, 0o644); err != nil {
			return nil, nil, err
		}
	}

	if err := runFlutterPubGetIn(workspace); err != nil {
		return nil, nil, fmt.Errorf("resolve Soroq build dependencies in an isolated workspace: %w", err)
	}

	generated := filepath.Join(workspace, ".dart_tool", "package_config.json")
	raw, err := os.ReadFile(generated)
	if err != nil {
		return nil, nil, fmt.Errorf("isolated resolution produced no package_config.json: %w", err)
	}
	// A missing lock is not fatal. The package_config is the artifact the build needs; the lock is an
	// additional consistency input for graph resolution, and callers fall back to the project's own when
	// it is absent. Failing here would turn a resolver that legitimately writes no lock into a hard build
	// error for a reason unrelated to the build.
	pinnedLock, lockErr := os.ReadFile(filepath.Join(workspace, "pubspec.lock"))
	if lockErr != nil {
		pinnedLock = nil
	}
	rewritten, err := rewritePackageConfigRoots(raw, packageName, projectDir, workspace)
	if err != nil {
		return nil, nil, err
	}
	return rewritten, pinnedLock, nil
}

// rewritePackageConfigRoots makes every rootUri absolute and repoints the ROOT package at the real
// project. Without that repoint the build would compile the workspace's (nonexistent) lib/ instead of
// the developer's source — the one way this design could silently build the wrong thing.
func rewritePackageConfigRoots(raw []byte, packageName, projectDir, workspace string) ([]byte, error) {
	var cfg map[string]any
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("parse generated package_config.json: %w", err)
	}
	packages, ok := cfg["packages"].([]any)
	if !ok {
		return nil, fmt.Errorf("generated package_config.json has no packages array")
	}
	// .dart_tool/package_config.json resolves relative rootUri values against its own directory.
	workspaceDartTool := filepath.Join(workspace, ".dart_tool")

	sawRoot := false
	for _, entry := range packages {
		pkg, ok := entry.(map[string]any)
		if !ok {
			continue
		}
		name, _ := pkg["name"].(string)
		if name == packageName {
			pkg["rootUri"] = "file://" + projectDir
			sawRoot = true
			continue
		}
		rootURI, _ := pkg["rootUri"].(string)
		abs, err := absolutePackageRootURI(rootURI, workspaceDartTool)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", name, err)
		}
		pkg["rootUri"] = abs
	}
	if !sawRoot {
		return nil, fmt.Errorf("resolved package config does not contain the project package %q", packageName)
	}
	// The installed file lives in the project's own .dart_tool/, so record that as the generator root.
	cfg["generator"] = "soroq"
	cfg["generatorVersion"] = "soroq-isolated-resolution"

	out, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// absolutePackageRootURI converts a possibly-relative rootUri into an absolute file:// URI. A rootUri
// left relative would resolve against the PROJECT's .dart_tool after install and silently point
// somewhere that does not exist.
func absolutePackageRootURI(rootURI, relativeTo string) (string, error) {
	trimmed := strings.TrimSpace(rootURI)
	if trimmed == "" {
		return "", fmt.Errorf("empty rootUri")
	}
	if strings.HasPrefix(trimmed, "file://") {
		return trimmed, nil
	}
	if filepath.IsAbs(trimmed) {
		return "file://" + trimmed, nil
	}
	return "file://" + filepath.Clean(filepath.Join(relativeTo, filepath.FromSlash(trimmed))), nil
}

// installPackageConfig writes package_config.json into the project's .dart_tool ATOMICALLY.
//
// A torn write would leave the project unbuildable by anything, so the bytes land in a sibling temp
// file and are renamed into place — a rename within one directory is atomic, so a concurrent build (or
// a crash) sees either the old file or the new one, never a partial one.
func installPackageConfig(projectDir string, data []byte) error {
	dartTool := filepath.Join(projectDir, ".dart_tool")
	if err := os.MkdirAll(dartTool, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dartTool, "package_config.json.soroq-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once the rename succeeds; cleans up every failure path
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, filepath.Join(dartTool, "package_config.json"))
}

// ---------------------------------------------------------------------------------------------------
// PLUGIN INJECTION vs THE LOCK
//
// `flutter pub get` does two jobs: it resolves packages, and it INJECTS plugin scaffolding — the
// generated plugin registrant, the CocoaPods symlinks, and the Swift Package Manager package that
// modern plugins (path_provider_foundation among them) are wired through. Skipping it with --no-pub
// therefore does not merely skip resolution; it leaves the SPM scaffolding stale, and the build dies
// with "Module 'path_provider_foundation' not found" inside GeneratedPluginRegistrant.m.
//
// So injection must run, in the project, with the frontend's Flutter. That rewrites pubspec.lock as a
// side effect — the very thing that must not persist.
//
// The guard below makes that side effect survivable rather than permanent, and it is NOT a naive
// "save, run, restore" (which loses the developer's lock if the process dies in between). The original
// bytes are written to .soroq/ FIRST, and every later run restores from that sidecar before doing
// anything else. A crash at any point leaves the lock recoverable, and the recovery is automatic:
//
//	write sidecar -> pub get (lock rewritten) -> restore from sidecar -> delete sidecar
//	          ^-- a crash anywhere here is repaired by restoreInterruptedLock on the NEXT run
//
// pubspec.yaml is never written at any point; only the lock is ever touched, and only transiently.

// lockGuardPath is where the developer's pubspec.lock is parked for the duration of an injection run.
// It lives under .soroq/ (git-ignored) so the sidecar itself is never a tracked change.
func lockGuardPath(projectDir string) string {
	return filepath.Join(projectDir, ".soroq", "lockguard", "pubspec.lock")
}

// restoreInterruptedLock repairs a lock left rewritten by a run that died before restoring it. It is
// called at the START of every resolution, so recovery needs no developer action and no `git checkout`.
func restoreInterruptedLock(projectDir string) error {
	guard := lockGuardPath(projectDir)
	saved, err := os.ReadFile(guard)
	if err != nil {
		return nil // no interrupted run to repair
	}
	lockPath := filepath.Join(projectDir, "pubspec.lock")
	if current, err := os.ReadFile(lockPath); err == nil && string(current) == string(saved) {
		// Already identical: the previous run restored it but died before clearing the sidecar.
		return os.Remove(guard)
	}
	if err := writeFileAtomic(lockPath, saved); err != nil {
		return fmt.Errorf("restore pubspec.lock after an interrupted Soroq build: %w", err)
	}
	fmt.Fprintf(os.Stderr, "soroq: restored pubspec.lock left rewritten by an interrupted build\n")
	return os.Remove(guard)
}

// runPluginInjection runs the frontend `flutter pub get` in the project so plugin scaffolding (registrant,
// CocoaPods symlinks, SPM package) matches the resolved plugins, then puts pubspec.lock back exactly as
// the developer had it.
func runPluginInjection(projectDir string) error {
	lockPath := filepath.Join(projectDir, "pubspec.lock")
	original, readErr := os.ReadFile(lockPath)
	hadLock := readErr == nil

	if hadLock {
		guard := lockGuardPath(projectDir)
		if err := os.MkdirAll(filepath.Dir(guard), 0o755); err != nil {
			return err
		}
		// Park the original BEFORE anything can rewrite it.
		if err := writeFileAtomic(guard, original); err != nil {
			return fmt.Errorf("park pubspec.lock before dependency injection: %w", err)
		}
	}

	injectErr := runFlutterPubGetIn(projectDir)

	if hadLock {
		if err := writeFileAtomic(lockPath, original); err != nil {
			// Leave the sidecar in place: the next run repairs it.
			return fmt.Errorf("restore pubspec.lock after dependency injection: %w", err)
		}
		if err := os.Remove(lockGuardPath(projectDir)); err != nil && !os.IsNotExist(err) {
			return err
		}
	} else if injectErr == nil {
		// There was no lock before; pub just created one. Removing it keeps the project exactly as the
		// developer left it — their own `pub get` will write the lock they intend to commit.
		_ = os.Remove(lockPath)
	}
	if injectErr != nil {
		return fmt.Errorf("resolve plugin scaffolding: %w", injectErr)
	}
	return nil
}

// pubspecWithAbsolutePathDependencies rewrites every relative `path:` dependency to an absolute path
// anchored at the real project directory.
//
// WHY. The isolated workspace is a temp directory, and the pubspec is copied into it verbatim. A
// relative path dependency — `path: ../../packages/soroq_flutter`, which every monorepo and every
// locally-developed plugin uses — then resolves against the TEMP directory and pub fails with
//
//	Because <app> depends on soroq_flutter from path which doesn't exist
//	(could not find package soroq_flutter at "../../packages/soroq_flutter")
//
// naming a path the developer's own project resolves perfectly well. The isolation is the point of
// the workspace, so the fix is to make the paths location-independent rather than to abandon it.
//
// Absolute paths are only rewritten INTO the workspace copy; the developer's pubspec.yaml on disk is
// never modified.
func pubspecWithAbsolutePathDependencies(text, projectDir string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "path:") {
			continue
		}
		value := strings.TrimSpace(strings.TrimPrefix(trimmed, "path:"))
		// Quoted forms are legal YAML; normalise before deciding, and re-emit unquoted since an
		// absolute POSIX path needs no quoting.
		value = strings.Trim(value, `"'`)
		if value == "" || filepath.IsAbs(value) {
			continue
		}
		indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
		lines[i] = indent + "path: " + filepath.Clean(filepath.Join(projectDir, value))
	}
	return strings.Join(lines, "\n")
}
